
service: whatsup-proxy
frameworkVersion: '2'
plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: whatsup-proxy
    corsAllowHeaders: 'Accept,Content-Type,Authorization'
    corsAllowOrigin: '*'
    httpPort: 4000

useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  memorySize: 128
  profile: dhruvsaraiya

functions:
  LoginToWhatsup:
     handler: handler.LoginToWhatsup
     events:
        - http: 
            path: LoginToWhatsup
            method: POST
            cors:
              origin: '*'
              headers:
                - Accept
                - Content-Type
                - Authorization
  GenerateOtp:
     handler: handler.GenerateOtp
     events:
        - http: 
            path: GenerateOtp
            method: POST
            cors:
              origin: '*'
              headers:
                - Accept
                - Content-Type
                - Authorization
  ReLoginToWhatsup:
     handler: handler.ReLoginToWhatsup
     events:
        - http: 
            path: ReLoginToWhatsup
            method: POST
            cors:
              origin: '*'
              headers:
                - Accept
                - Content-Type
                - Authorization
