
service: whatsup-proxy
frameworkVersion: '2'
plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: whatsup-proxy
    corsAllowHeaders: 'Accept,Content-Type,Authorization,Accept-Encoding,Accept-Language,Connection,Content-Length,Host,Origin,Referer,User-Agent'
    corsAllowOrigin: '*'
    httpPort: 4000

useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  memorySize: 128
  profile: dhruvsaraiya

functions:
  loginToWhatsup:
     handler: handler.loginToWhatsup
     events:
        - http: 
            path: loginToWhatsup
            method: POST
            cors:
              origin: '*'
              headers:
                - Accept
                - Content-Type
                - Authorization
                - Accept-Encoding
                - Accept-Language
                - Connection
                - Content-Length
                - Host
                - Origin
                - Referer
                - User-Agent
              allowCredentials: true
     environment:
       WHATSUP_API_KEY: ${env:WHATSUP_API_KEY}
       WHATSUP_BASE_URL: ${env:WHATSUP_BASE_URL}
